spring.application.name=api-rest-security-jwt

server.port=8062
spring.datasource.url=jdbc:mysql://localhost:3306/securitydbrest?useSSL=false
spring.datasource.username=root
spring.datasource.password=admin2024
